/* Generated By:JavaCC: Do not edit this line. TsurgeonParserTreeConstants.java Version 7.0.9 */
package edu.stanford.nlp.trees.tregex.tsurgeon;

public interface TsurgeonParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTOPERATION = 1;
  public int JJTLOCATION = 2;
  public int JJTNODESELECTIONLIST = 3;
  public int JJTNODESELECTION = 4;
  public int JJTNODENAME = 5;
  public int JJTTREELIST = 6;
  public int JJTTREEROOT = 7;
  public int JJTTREENODE = 8;
  public int JJTTREEDTRS = 9;


  public String[] jjtNodeName = {
    "Root",
    "Operation",
    "Location",
    "NodeSelectionList",
    "NodeSelection",
    "NodeName",
    "TreeList",
    "TreeRoot",
    "TreeNode",
    "TreeDtrs",
  };
}
/* JavaCC - OriginalChecksum=b15374fec4b618687fa21f03842f809a (do not edit this line) */
