/* Generated By:JavaCC: Do not edit this line. TsurgeonParserTreeConstants.java Version 5.0 */
package edu.stanford.nlp.trees.tregex.tsurgeon;

public interface TsurgeonParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTOPERATION = 1;
  public int JJTLOCATION = 2;
  public int JJTNODESELECTIONLIST = 3;
  public int JJTNODESELECTION = 4;
  public int JJTNODENAME = 5;
  public int JJTTREEROOT = 6;
  public int JJTTREENODE = 7;
  public int JJTTREEDTRS = 8;


  public String[] jjtNodeName = {
    "Root",
    "Operation",
    "Location",
    "NodeSelectionList",
    "NodeSelection",
    "NodeName",
    "TreeRoot",
    "TreeNode",
    "TreeDtrs",
  };
}
/* JavaCC - OriginalChecksum=f768a367fd45fc9272bb40a8f1af56ce (do not edit this line) */
