(tag-map 

;; Abbreviations and other odds and ends
ABBREV	ABBREV
DET+ABBREV	ABBREV
DET+DIALECT	DTNN
DET+FOREIGN	DTNN
DET+NOUN	DTNN
DET+TYPO	DTNN
DIALECT	NN
FOREIGN	NN
GRAMMAR_PROBLEM	NN
LATIN	NN
TYPO	NN

;; Punctuation (The other PUNC terminals just pass through)
NUMERIC_COMMA	PUNC

;; Ordinals e.g. "15", "12-17"
NOUN_NUM	CD

;; What are these?
CV	VB
CV+CVSUFF_SUBJ:2FS	VB
CV+CVSUFF_SUBJ:2MP	VB
CV+CVSUFF_SUBJ:2MS	VB

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Adjectives ... MUST DO SOMETHING HERE!!
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ADJ	JJ
ADJ+CASE_DEF_ACC	JJ
ADJ+CASE_DEF_GEN	JJ
ADJ+CASE_DEF_NOM	JJ
ADJ+CASE_INDEF_ACC	JJ
ADJ+CASE_INDEF_GEN	JJ
ADJ+CASE_INDEF_NOM	JJ
ADJ+NSUFF_FEM_DU_ACC	JJ+F
ADJ+NSUFF_FEM_DU_ACCGEN	JJ+F
ADJ+NSUFF_FEM_DU_GEN	JJ+F
ADJ+NSUFF_FEM_DU_NOM	JJ+F
ADJ+NSUFF_FEM_DU_NOM_POSS	JJ+F
ADJ+NSUFF_FEM_PL	JJ+F
ADJ+NSUFF_FEM_PL+CASE_DEF_ACCGEN	DTJJ+F
ADJ+NSUFF_FEM_PL+CASE_DEF_NOM	JJ+F
ADJ+NSUFF_FEM_PL+CASE_INDEF_ACC	JJ+F
ADJ+NSUFF_FEM_PL+CASE_INDEF_ACCGEN	JJ+F
ADJ+NSUFF_FEM_PL+CASE_INDEF_GEN	JJ+F
ADJ+NSUFF_FEM_SG	JJ+F
ADJ+NSUFF_FEM_SG+CASE_DEF_ACC	JJ+F
ADJ+NSUFF_FEM_SG+CASE_DEF_GEN	JJ+F
ADJ+NSUFF_FEM_SG+CASE_DEF_NOM	JJ+F
ADJ+NSUFF_FEM_SG+CASE_INDEF_ACC	JJ+F
ADJ+NSUFF_FEM_SG+CASE_INDEF_GEN	JJ+F
ADJ+NSUFF_FEM_SG+CASE_INDEF_NOM	JJ+F
ADJ+NSUFF_MASC_DU_ACC	JJ
ADJ+NSUFF_MASC_DU_ACCGEN	JJ
ADJ+NSUFF_MASC_DU_ACCGEN_POSS	JJ
ADJ+NSUFF_MASC_DU_GEN	JJ
ADJ+NSUFF_MASC_DU_GEN_POSS	JJ
ADJ+NSUFF_MASC_DU_NOM	JJ
ADJ+NSUFF_MASC_DU_NOM_POSS	JJ
ADJ+NSUFF_MASC_PL_ACC	JJ
ADJ+NSUFF_MASC_PL_ACCGEN	JJ
ADJ+NSUFF_MASC_PL_ACCGEN_POSS	JJ
ADJ+NSUFF_MASC_PL_ACC_POSS	JJ
ADJ+NSUFF_MASC_PL_GEN	JJ
ADJ+NSUFF_MASC_PL_GEN_POSS	JJ
ADJ+NSUFF_MASC_PL_NOM	JJ
ADJ+NSUFF_MASC_PL_NOM_POSS	JJ
DET+ADJ	DTJJ
DET+ADJ+CASE_DEF_ACC	DTJJ
DET+ADJ+CASE_DEF_GEN	DTJJ
DET+ADJ+CASE_DEF_NOM	DTJJ
DET+ADJ+NSUFF_FEM_DU_ACC	DTJJ+F
DET+ADJ+NSUFF_FEM_DU_ACCGEN	DTJJ+F
DET+ADJ+NSUFF_FEM_DU_ACCGEN_POSS	DTJJ+F
DET+ADJ+NSUFF_FEM_DU_GEN	DTJJ+F
DET+ADJ+NSUFF_FEM_DU_NOM	DTJJ+F
DET+ADJ+NSUFF_FEM_PL+CASE_DEF_ACC	DTJJ+F
DET+ADJ+NSUFF_FEM_PL+CASE_DEF_ACCGEN	DTJJ+F
DET+ADJ+NSUFF_FEM_PL+CASE_DEF_GEN	DTJJ+F
DET+ADJ+NSUFF_FEM_PL+CASE_DEF_NOM	DTJJ+F
DET+ADJ+NSUFF_FEM_SG	DTJJ+F
DET+ADJ+NSUFF_FEM_SG+CASE_DEF_ACC	DTJJ+F
DET+ADJ+NSUFF_FEM_SG+CASE_DEF_GEN	DTJJ+F
DET+ADJ+NSUFF_FEM_SG+CASE_DEF_NOM	DTJJ+F
DET+ADJ+NSUFF_MASC_DU_ACC	DTJJ
DET+ADJ+NSUFF_MASC_DU_ACCGEN	DTJJ
DET+ADJ+NSUFF_MASC_DU_GEN	DTJJ
DET+ADJ+NSUFF_MASC_DU_NOM	DTJJ
DET+ADJ+NSUFF_MASC_PL_ACC	DTJJ
DET+ADJ+NSUFF_MASC_PL_ACCGEN	DTJJ
DET+ADJ+NSUFF_MASC_PL_ACCGEN_POSS	DTJJ
DET+ADJ+NSUFF_MASC_PL_ACC_POSS	DTJJ
DET+ADJ+NSUFF_MASC_PL_GEN	DTJJ
DET+ADJ+NSUFF_MASC_PL_GEN_POSS	DTJJ
DET+ADJ+NSUFF_MASC_PL_NOM	DTJJ

;; Change this and the ADJP to Idafa
ADJ_COMP	JJR
ADJ_COMP+CASE_DEF_ACC	JJR
ADJ_COMP+CASE_DEF_GEN	JJR
ADJ_COMP+CASE_DEF_NOM	JJR
ADJ_COMP+CASE_INDEF_ACC	JJR
ADJ_COMP+CASE_INDEF_GEN	JJR
ADJ_COMP+CASE_INDEF_NOM	JJR
ADJ_COMP+NSUFF_FEM_SG+CASE_INDEF_NOM	JJR+F
DET+ADJ_COMP	DTJJR
DET+ADJ_COMP+CASE_DEF_ACC	DTJJR
DET+ADJ_COMP+CASE_DEF_GEN	DTJJR
DET+ADJ_COMP+CASE_DEF_NOM	DTJJR
DET+ADJ_COMP+NSUFF_MASC_DU_GEN	DTJJR
DET+ADJ_COMP+NSUFF_MASC_PL_GEN	DTJJR
DET+ADJ_COMP+NSUFF_MASC_PL_NOM	DTJJR

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Verbal nouns --> MUST DO SOMETHING HERE!!
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Adjectival VNs...should collapse these?
ADJ.VN	VN
ADJ.VN+CASE_DEF_GEN	VN
ADJ.VN+CASE_DEF_NOM	VN
ADJ.VN+CASE_INDEF_ACC	VN
ADJ.VN+CASE_INDEF_GEN	VN
ADJ.VN+CASE_INDEF_NOM	VN
ADJ.VN+NSUFF_FEM_DU_ACC	VN+F
ADJ.VN+NSUFF_FEM_SG	VN+F
ADJ.VN+NSUFF_FEM_SG+CASE_DEF_ACC	VN+F
ADJ.VN+NSUFF_FEM_SG+CASE_DEF_GEN	VN+F
ADJ.VN+NSUFF_FEM_SG+CASE_INDEF_ACC	VN+F
ADJ.VN+NSUFF_FEM_SG+CASE_INDEF_GEN	VN+F
ADJ.VN+NSUFF_FEM_SG+CASE_INDEF_NOM	VN+F
ADJ.VN+NSUFF_MASC_DU_ACC	VN
ADJ.VN+NSUFF_MASC_DU_GEN	VN
ADJ.VN+NSUFF_MASC_DU_NOM_POSS	VN
ADJ.VN+NSUFF_MASC_PL_ACC	VN
ADJ.VN+NSUFF_MASC_PL_ACCGEN	VN
ADJ.VN+NSUFF_MASC_PL_GEN	VN
ADJ.VN+NSUFF_MASC_PL_NOM	VN
DET+ADJ.VN	DTVN
DET+ADJ.VN+CASE_DEF_ACC	DTVN
DET+ADJ.VN+CASE_DEF_GEN	DTVN
DET+ADJ.VN+CASE_DEF_NOM	DTVN
DET+ADJ.VN+NSUFF_FEM_DU_ACC	DTVN+F
DET+ADJ.VN+NSUFF_FEM_DU_GEN	DTVN+F
DET+ADJ.VN+NSUFF_FEM_PL+CASE_DEF_GEN	DTVN+F
DET+ADJ.VN+NSUFF_FEM_PL+CASE_DEF_NOM	DTVN+F
DET+ADJ.VN+NSUFF_FEM_SG	DTVN+F
DET+ADJ.VN+NSUFF_FEM_SG+CASE_DEF_ACC	DTVN+F
DET+ADJ.VN+NSUFF_FEM_SG+CASE_DEF_GEN	DTVN+F
DET+ADJ.VN+NSUFF_FEM_SG+CASE_DEF_NOM	DTVN+F
DET+ADJ.VN+NSUFF_MASC_DU_ACC	DTVN
DET+ADJ.VN+NSUFF_MASC_DU_GEN	DTVN
DET+ADJ.VN+NSUFF_MASC_PL_ACC	DTVN
DET+ADJ.VN+NSUFF_MASC_PL_ACCGEN	DTVN
DET+ADJ.VN+NSUFF_MASC_PL_GEN	DTVN
DET+ADJ.VN+NSUFF_MASC_PL_NOM	DTVN

;; Formerly VBG...Collapse into VN
DET+NOUN.VN	DTVN
DET+NOUN.VN+CASE_DEF_ACC	DTVN
DET+NOUN.VN+CASE_DEF_GEN	DTVN
DET+NOUN.VN+CASE_DEF_NOM	DTVN
DET+NOUN.VN+NSUFF_FEM_DU_GEN	DTVN+F
DET+NOUN.VN+NSUFF_FEM_SG+CASE_DEF_ACC	DTVN+F
DET+NOUN.VN+NSUFF_FEM_SG+CASE_DEF_GEN	DTVN+F
DET+NOUN.VN+NSUFF_FEM_SG+CASE_DEF_NOM	DTVN+F
DET+NOUN.VN+NSUFF_MASC_DU_NOM	DTVN
DET+NOUN.VN+NSUFF_MASC_PL_ACC	DTVN
DET+NOUN.VN+NSUFF_MASC_PL_ACCGEN	DTVN
DET+NOUN.VN+NSUFF_MASC_PL_GEN	DTVN
DET+NOUN.VN+NSUFF_MASC_PL_NOM	DTVN
NOUN.VN	VN
NOUN.VN+CASE_DEF_ACC	VN
NOUN.VN+CASE_DEF_GEN	VN
NOUN.VN+CASE_DEF_NOM	VN
NOUN.VN+CASE_INDEF_ACC	VN
NOUN.VN+CASE_INDEF_GEN	VN
NOUN.VN+CASE_INDEF_NOM	VN
NOUN.VN+NSUFF_FEM_DU_ACC	VN+F
NOUN.VN+NSUFF_FEM_PL+CASE_DEF_ACC	VN+F
NOUN.VN+NSUFF_FEM_PL+CASE_DEF_ACCGEN	VN+F
NOUN.VN+NSUFF_FEM_PL+CASE_DEF_GEN	VN+F
NOUN.VN+NSUFF_FEM_PL+CASE_DEF_NOM	VN+F
NOUN.VN+NSUFF_FEM_SG	VN+F
NOUN.VN+NSUFF_FEM_SG+CASE_DEF_ACC	VN+F
NOUN.VN+NSUFF_FEM_SG+CASE_DEF_GEN	VN+F
NOUN.VN+NSUFF_FEM_SG+CASE_DEF_NOM	VN+F
NOUN.VN+NSUFF_FEM_SG+CASE_INDEF_ACC	VN+F
NOUN.VN+NSUFF_FEM_SG+CASE_INDEF_GEN	VN+F
NOUN.VN+NSUFF_FEM_SG+CASE_INDEF_NOM	VN+F
NOUN.VN+NSUFF_MASC_DU_GEN	VN
NOUN.VN+NSUFF_MASC_PL_ACC	VN
NOUN.VN+NSUFF_MASC_PL_ACCGEN	VN
NOUN.VN+NSUFF_MASC_PL_NOM	VN

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Misc stuff
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Adverbs
ADV	RB
ADV+CASE_INDEF_ACC	RB

;; Conjunctions (do additional splits in the mapper)
CONJ	CC
CONNEC_PART	FA

;; Pronouns (segmented and unsegmented) (segmentation markers detected in mapping and a $ added)
CVSUFF_DO:1P	PRP
CVSUFF_DO:1S	PRP
CVSUFF_DO:3FS	PRP
CVSUFF_DO:3MP	PRP
CVSUFF_DO:3MS	PRP
IVSUFF_DO:1P	PRP
IVSUFF_DO:1S	PRP
IVSUFF_DO:2FS	PRP
IVSUFF_DO:2MP	PRP
IVSUFF_DO:2MS	PRP
IVSUFF_DO:3D	PRP
IVSUFF_DO:3FS	PRP
IVSUFF_DO:3MP	PRP
IVSUFF_DO:3MS	PRP
POSS_PRON_1P	PRP
POSS_PRON_1S	PRP
POSS_PRON_2FP	PRP
POSS_PRON_2FS	PRP
POSS_PRON_2MP	PRP
POSS_PRON_2MS	PRP
POSS_PRON_3D	PRP
POSS_PRON_3FP	PRP
POSS_PRON_3FS	PRP
POSS_PRON_3MP	PRP
POSS_PRON_3MS	PRP
PVSUFF_DO:1P	PRP
PVSUFF_DO:1S	PRP
PVSUFF_DO:2FS	PRP
PVSUFF_DO:2MP	PRP
PVSUFF_DO:2MS	PRP
PVSUFF_DO:3D	PRP
PVSUFF_DO:3FS	PRP
PVSUFF_DO:3MP	PRP
PVSUFF_DO:3MS	PRP
PRON	PRP
PRON_1P	PRP
PRON_1S	PRP
PRON_2D	PRP
PRON_2FP	PRP
PRON_2FS	PRP
PRON_2MP	PRP
PRON_2MS	PRP
PRON_3D	PRP
PRON_3FP	PRP
PRON_3FS	PRP
PRON_3MP	PRP
PRON_3MS	PRP

;; Determiners
DEM_PRON	DT
DEM_PRON_F	DT
DEM_PRON_FD	DT
DEM_PRON_FS	DT
DEM_PRON_MD	DT
DEM_PRON_MP	DT
DEM_PRON_MS	DT
DET	DT

;; Quantifiers (Old NOUN_QUANT category)
DET+NOUN_QUANT+CASE_DEF_ACC	DTNN
DET+NOUN_QUANT+CASE_DEF_GEN	DTNN
DET+NOUN_QUANT+CASE_DEF_NOM	DTNN
DET+NOUN_QUANT+NSUFF_FEM_SG+CASE_DEF_ACC	DTNN+F
DET+NOUN_QUANT+NSUFF_FEM_SG+CASE_DEF_GEN	DTNN+F
DET+NOUN_QUANT+NSUFF_FEM_SG+CASE_DEF_NOM	DTNN+F
NOUN_QUANT	NN
NOUN_QUANT+CASE_DEF_ACC	NN
NOUN_QUANT+CASE_DEF_GEN	NN
NOUN_QUANT+CASE_DEF_NOM	NN
NOUN_QUANT+CASE_INDEF_ACC	NN
NOUN_QUANT+CASE_INDEF_GEN	NN
NOUN_QUANT+CASE_INDEF_NOM	NN
NOUN_QUANT+NSUFF_FEM_SG+CASE_DEF_ACC	NN+F
NOUN_QUANT+NSUFF_FEM_SG+CASE_DEF_GEN	NN+F
NOUN_QUANT+NSUFF_FEM_SG+CASE_DEF_NOM	NN+F
NOUN_QUANT+NSUFF_FEM_SG+CASE_INDEF_ACC	NN+F
NOUN_QUANT+NSUFF_FEM_SG+CASE_INDEF_GEN	NN+F
NOUN_QUANT+NSUFF_MASC_DU_ACC_POSS	NN
NOUN_QUANT+NSUFF_MASC_DU_GEN	NN
NOUN_QUANT+NSUFF_MASC_DU_GEN_POSS	NN
NOUN_QUANT+NSUFF_MASC_DU_NOM_POSS	NN

;; Appear under WHNP
EXCLAM_PRON	WP
INTERROG_PRON	WP
INTERROG_PRON+CASE_DEF_GEN	WP
INTERROG_PRON+CASE_DEF_NOM	WP
INTERROG_PRON+NSUFF_FEM_SG+CASE_DEF_GEN	WP
REL_PRON	WP
REL_PRON+CASE_DEF_ACC	WP
REL_PRON+CASE_DEF_GEN	WP
REL_PRON+CASE_DEF_NOM	WP
REL_PRON+CASE_INDEF_ACC	WP
REL_PRON+NSUFF_FEM_SG+CASE_DEF_GEN	WP
REL_PRON+NSUFF_MASC_SG_ACC_INDEF	WP

;; Appear under PRT
EMPHATIC_PART	RP
FOCUS_PART	RP
INTERROG_PART	RP

;; Appear under WHADV 
INTERROG_ADV	WRB
REL_ADV	WRB


INTERJ	UH

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Nouns
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
DET+NOUN+CASE_DEF_ACC	DTNN
DET+NOUN+CASE_DEF_GEN	DTNN
DET+NOUN+CASE_DEF_NOM	DTNN
DET+NOUN+NSUFF_FEM_DU_ACC	DTNNS+F
DET+NOUN+NSUFF_FEM_DU_ACCGEN	DTNNS+F
DET+NOUN+NSUFF_FEM_DU_GEN	DTNNS+F
DET+NOUN+NSUFF_FEM_DU_GEN_POSS	DTNNS+F
DET+NOUN+NSUFF_FEM_DU_NOM	DTNNS+F
DET+NOUN+NSUFF_FEM_PL	DTNNS+F
DET+NOUN+NSUFF_FEM_PL+CASE_DEF_ACC	DTNNS+F
DET+NOUN+NSUFF_FEM_PL+CASE_DEF_ACCGEN	DTNNS+F
DET+NOUN+NSUFF_FEM_PL+CASE_DEF_GEN	DTNNS+F
DET+NOUN+NSUFF_FEM_PL+CASE_DEF_NOM	DTNNS+F
DET+NOUN+NSUFF_FEM_SG	DTNN+F
DET+NOUN+NSUFF_FEM_SG+CASE_DEF_ACC	DTNN+F
DET+NOUN+NSUFF_FEM_SG+CASE_DEF_GEN	DTNN+F
DET+NOUN+NSUFF_FEM_SG+CASE_DEF_NOM	DTNN+F
DET+NOUN+NSUFF_MASC_DU	DTNNS
DET+NOUN+NSUFF_MASC_DU_ACC	DTNNS
DET+NOUN+NSUFF_MASC_DU_ACCGEN	DTNNS
DET+NOUN+NSUFF_MASC_DU_GEN	DTNNS
DET+NOUN+NSUFF_MASC_DU_GEN_POSS	DTNNS
DET+NOUN+NSUFF_MASC_DU_NOM	DTNNS
DET+NOUN+NSUFF_MASC_PL_ACC	DTNNS
DET+NOUN+NSUFF_MASC_PL_ACCGEN	DTNNS
DET+NOUN+NSUFF_MASC_PL_GEN	DTNNS
DET+NOUN+NSUFF_MASC_PL_GEN_POSS	DTNNS
DET+NOUN+NSUFF_MASC_PL_NOM	DTNNS
DET+NOUN_PROP	DTNNP
DET+NOUN_PROP+CASE_DEF_ACC	DTNNP
DET+NOUN_PROP+CASE_DEF_GEN	DTNNP
DET+NOUN_PROP+CASE_DEF_NOM	DTNNP
DET+NOUN_PROP+NSUFF_FEM_DU_GEN	DTNNPS+F
DET+NOUN_PROP+NSUFF_FEM_DU_NOM	DTNNPS+F
DET+NOUN_PROP+NSUFF_FEM_PL	DTNNPS+F+
DET+NOUN_PROP+NSUFF_FEM_PL+CASE_DEF_ACCGEN	DTNNPS+F
DET+NOUN_PROP+NSUFF_FEM_PL+CASE_DEF_GEN	DTNNPS+F
DET+NOUN_PROP+NSUFF_FEM_SG	DTNNP+F
DET+NOUN_PROP+NSUFF_FEM_SG+CASE_DEF_ACC	DTNNP+F
DET+NOUN_PROP+NSUFF_FEM_SG+CASE_DEF_GEN	DTNNP+F
DET+NOUN_PROP+NSUFF_FEM_SG+CASE_DEF_NOM	DTNNP+F
DET+NOUN_PROP+NSUFF_MASC_DU_ACCGEN	DTNNPS
DET+NOUN_PROP+NSUFF_MASC_DU_GEN	DTNNPS
DET+NOUN_PROP+NSUFF_MASC_PL_ACC	DTNNPS
DET+NOUN_PROP+NSUFF_MASC_PL_GEN	DTNNPS
DET+NOUN_PROP+NSUFF_MASC_PL_NOM	DTNNPS
NOUN	NN
NOUN+CASE_DEF_ACC	NN
NOUN+CASE_DEF_GEN	NN
NOUN+CASE_DEF_NOM	NN
NOUN+CASE_INDEF_ACC	NN
NOUN+CASE_INDEF_GEN	NN
NOUN+CASE_INDEF_NOM	NN
NOUN+NSUFF_FEM_DU_ACC	NNS+F
NOUN+NSUFF_FEM_DU_ACCGEN	NNS+F
NOUN+NSUFF_FEM_DU_ACCGEN_POSS	NNS+F
NOUN+NSUFF_FEM_DU_ACC_POSS	NNS+F
NOUN+NSUFF_FEM_DU_GEN	NNS+F
NOUN+NSUFF_FEM_DU_GEN_POSS	NNS+F
NOUN+NSUFF_FEM_DU_NOM	NNS+F
NOUN+NSUFF_FEM_DU_NOM_POSS	NNS+F
NOUN+NSUFF_FEM_PL	NNS+F
NOUN+NSUFF_FEM_PL+CASE_DEF_ACC	NNS+F
NOUN+NSUFF_FEM_PL+CASE_DEF_ACCGEN	NNS+F
NOUN+NSUFF_FEM_PL+CASE_DEF_GEN	NNS+F
NOUN+NSUFF_FEM_PL+CASE_DEF_NOM	NNS+F
NOUN+NSUFF_FEM_PL+CASE_INDEF_ACC	NNS+F
NOUN+NSUFF_FEM_PL+CASE_INDEF_ACCGEN	NNS+F
NOUN+NSUFF_FEM_PL+CASE_INDEF_GEN	NNS+F
NOUN+NSUFF_FEM_PL+CASE_INDEF_NOM	NNS+F
NOUN+NSUFF_FEM_SG	NN+F
NOUN+NSUFF_FEM_SG+CASE_DEF_ACC	NN+F
NOUN+NSUFF_FEM_SG+CASE_DEF_GEN	NN+F
NOUN+NSUFF_FEM_SG+CASE_DEF_NOM	NN+F
NOUN+NSUFF_FEM_SG+CASE_INDEF_ACC	NN+F
NOUN+NSUFF_FEM_SG+CASE_INDEF_GEN	NN+F
NOUN+NSUFF_FEM_SG+CASE_INDEF_NOM	NN+F
NOUN+NSUFF_MASC_DU	NNS
NOUN+NSUFF_MASC_DU_ACC	NNS
NOUN+NSUFF_MASC_DU_ACCGEN	NNS
NOUN+NSUFF_MASC_DU_ACCGEN_POSS	NNS
NOUN+NSUFF_MASC_DU_ACC_POSS	NNS
NOUN+NSUFF_MASC_DU_GEN	NNS
NOUN+NSUFF_MASC_DU_GEN_POSS	NNS
NOUN+NSUFF_MASC_DU_NOM	NNS
NOUN+NSUFF_MASC_DU_NOM_POSS	NNS
NOUN+NSUFF_MASC_PL_ACC	NNS
NOUN+NSUFF_MASC_PL_ACCGEN	NNS
NOUN+NSUFF_MASC_PL_ACCGEN_POSS	NNS
NOUN+NSUFF_MASC_PL_ACC_POSS	NNS
NOUN+NSUFF_MASC_PL_GEN	NNS
NOUN+NSUFF_MASC_PL_GEN_POSS	NNS
NOUN+NSUFF_MASC_PL_NOM	NNS
NOUN+NSUFF_MASC_PL_NOM_POSS	NNS
NOUN+NSUFF_MASC_SG_ACC_INDEF	NN
NOUN_PROP	NNP
NOUN_PROP+CASE_DEF_ACC	NNP
NOUN_PROP+CASE_DEF_GEN	NNP
NOUN_PROP+CASE_DEF_NOM	NNP
NOUN_PROP+CASE_INDEF_ACC	NNP
NOUN_PROP+CASE_INDEF_GEN	NNP
NOUN_PROP+CASE_INDEF_NOM	NNP
NOUN_PROP+NSUFF_FEM_PL+CASE_DEF_GEN	NNPS+F
NOUN_PROP+NSUFF_FEM_PL+CASE_INDEF_ACCGEN	NNPS+F
NOUN_PROP+NSUFF_FEM_PL+CASE_INDEF_GEN	NNPS+F
NOUN_PROP+NSUFF_FEM_SG	NNP+F
NOUN_PROP+NSUFF_FEM_SG+CASE_DEF_ACC	NNP+F
NOUN_PROP+NSUFF_FEM_SG+CASE_DEF_GEN	NNP+F
NOUN_PROP+NSUFF_FEM_SG+CASE_DEF_NOM	NNP+F
NOUN_PROP+NSUFF_FEM_SG+CASE_INDEF_ACC	NNP+F
NOUN_PROP+NSUFF_FEM_SG+CASE_INDEF_GEN	NNP+F
NOUN_PROP+NSUFF_FEM_SG+CASE_INDEF_NOM	NNP+F
NOUN_PROP+NSUFF_MASC_PL_GEN_POSS	NNPS
NOUN_PROP+NSUFF_MASC_PL_NOM	NNPS

;; Noun particles
VOC_PART	NRP


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; NOUN_NUM was formerly CD; ADJ_NUM was formerly ADJ_NUM (cardinal)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
DET+NOUN_NUM+CASE_DEF_ACC	DTNN
DET+NOUN_NUM+CASE_DEF_GEN	DTNN
DET+NOUN_NUM+NSUFF_FEM_SG+CASE_DEF_ACC	DTNN+F
DET+NOUN_NUM+NSUFF_FEM_SG+CASE_DEF_GEN	DTNN+F
DET+NOUN_NUM+NSUFF_FEM_SG+CASE_DEF_NOM	DTNN+F
DET+NOUN_NUM+NSUFF_MASC_DU_NOM	DTNN
DET+NOUN_NUM+NSUFF_MASC_PL_ACC	DTNN
DET+NOUN_NUM+NSUFF_MASC_PL_GEN	DTNN
DET+NOUN_NUM+NSUFF_MASC_PL_NOM	DTNN
NOUN_NUM+CASE_DEF_ACC	NN
NOUN_NUM+CASE_DEF_GEN	NN
NOUN_NUM+CASE_DEF_NOM	NN
NOUN_NUM+CASE_INDEF_ACC	NN
NOUN_NUM+CASE_INDEF_GEN	NN
NOUN_NUM+CASE_INDEF_NOM	NN
NOUN_NUM+NSUFF_FEM_DU_ACC	NN+F
NOUN_NUM+NSUFF_FEM_DU_GEN	NN+F
NOUN_NUM+NSUFF_FEM_DU_GEN_POSS	NN+F
NOUN_NUM+NSUFF_FEM_PL+CASE_DEF_ACC	NN+F
NOUN_NUM+NSUFF_FEM_PL+CASE_DEF_ACCGEN	NN+F
NOUN_NUM+NSUFF_FEM_PL+CASE_DEF_GEN	NN+F
NOUN_NUM+NSUFF_FEM_PL+CASE_DEF_NOM	NN+F
NOUN_NUM+NSUFF_FEM_PL+CASE_INDEF_NOM	NN+F
NOUN_NUM+NSUFF_FEM_SG+CASE_DEF_ACC	NN+F
NOUN_NUM+NSUFF_FEM_SG+CASE_DEF_GEN	NN+F
NOUN_NUM+NSUFF_FEM_SG+CASE_DEF_NOM	NN+F
NOUN_NUM+NSUFF_FEM_SG+CASE_INDEF_ACC	NN+F
NOUN_NUM+NSUFF_FEM_SG+CASE_INDEF_GEN	NN+F
NOUN_NUM+NSUFF_FEM_SG+CASE_INDEF_NOM	NN+F
NOUN_NUM+NSUFF_MASC_DU_ACCGEN_POSS	NN+F
NOUN_NUM+NSUFF_MASC_DU_ACC_POSS	NN
NOUN_NUM+NSUFF_MASC_DU_GEN	NN
NOUN_NUM+NSUFF_MASC_DU_GEN_POSS	NN
NOUN_NUM+NSUFF_MASC_DU_NOM	NN
NOUN_NUM+NSUFF_MASC_DU_NOM_POSS	NN
NOUN_NUM+NSUFF_MASC_PL_ACC	NN
NOUN_NUM+NSUFF_MASC_PL_ACCGEN	NN
NOUN_NUM+NSUFF_MASC_PL_ACC_POSS	NN
NOUN_NUM+NSUFF_MASC_PL_GEN	NN
NOUN_NUM+NSUFF_MASC_PL_NOM	NN
ADJ_NUM	JJNUM
ADJ_NUM+CASE_DEF_ACC	JJNUM
ADJ_NUM+CASE_DEF_GEN	JJNUM
ADJ_NUM+CASE_DEF_NOM	JJNUM
ADJ_NUM+CASE_INDEF_ACC	JJNUM
ADJ_NUM+CASE_INDEF_GEN	JJNUM
ADJ_NUM+CASE_INDEF_NOM	JJNUM
ADJ_NUM+NSUFF_FEM_DU_GEN	JJNUM+F
ADJ_NUM+NSUFF_FEM_SG+CASE_DEF_ACC	JJNUM+F
ADJ_NUM+NSUFF_FEM_SG+CASE_DEF_GEN	JJNUM+F
ADJ_NUM+NSUFF_FEM_SG+CASE_DEF_NOM	JJNUM+F
ADJ_NUM+NSUFF_FEM_SG+CASE_INDEF_ACC	JJNUM+F
ADJ_NUM+NSUFF_FEM_SG+CASE_INDEF_GEN	JJNUM+F
ADJ_NUM+NSUFF_FEM_SG+CASE_INDEF_NOM	JJNUM+F
DET+ADJ_NUM	DTJJNUM
DET+ADJ_NUM+CASE_DEF_ACC	DTJJNUM
DET+ADJ_NUM+CASE_DEF_GEN	DTJJNUM
DET+ADJ_NUM+CASE_DEF_NOM	DTJJNUM
DET+ADJ_NUM+NSUFF_FEM_PL+CASE_DEF_GEN	DTJJNUM+F
DET+ADJ_NUM+NSUFF_FEM_PL+CASE_DEF_NOM	DTJJNUM+F
DET+ADJ_NUM+NSUFF_FEM_SG	DTJJNUM+F
DET+ADJ_NUM+NSUFF_FEM_SG+CASE_DEF_ACC	DTJJNUM+F
DET+ADJ_NUM+NSUFF_FEM_SG+CASE_DEF_GEN	DTJJNUM+F
DET+ADJ_NUM+NSUFF_FEM_SG+CASE_DEF_NOM	DTJJNUM+F
DET+ADJ_NUM+NSUFF_MASC_DU_ACC	DTJJNUM
DET+ADJ_NUM+NSUFF_MASC_DU_GEN	DTJJNUM
DET+ADJ_NUM+NSUFF_MASC_DU_NOM	DTJJNUM
DET+ADJ_NUM+NSUFF_MASC_PL_ACCGEN	DTJJNUM
DET+ADJ_NUM+NSUFF_MASC_PL_GEN	DTJJNUM

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Verbs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
FUT+IV1P+IV+IVSUFF_MOOD:I	VBP
FUT+IV1S+IV+IVSUFF_MOOD:I	VBP
FUT+IV2MP+IV+IVSUFF_SUBJ:MP_MOOD:I	VBP
FUT+IV2MS+IV+IVSUFF_MOOD:I	VBP
FUT+IV3FD+IV+IVSUFF_SUBJ:D_MOOD:I	VBP
FUT+IV3FS+IV+IVSUFF_MOOD:I	VBP
FUT+IV3FS+IV_PASS+IVSUFF_MOOD:I	VBN
FUT+IV3MD+IV+IVSUFF_SUBJ:D_MOOD:I	VBP
FUT+IV3MD+IV_PASS+IVSUFF_SUBJ:D_MOOD:I	VBN
FUT+IV3MP+IV+IVSUFF_SUBJ:MP_MOOD:I	VBP
FUT+IV3MP+IV_PASS+IVSUFF_SUBJ:MP_MOOD:I	VBN
FUT+IV3MS+IV+IVSUFF_MOOD:I	VBP
FUT+IV3MS+IV_PASS+IVSUFF_MOOD:I	VBN
FUT+IV3MS+IV_PASS+IVSUFF_MOOD:S	VBN
IV	VBP
IV+IVSUFF_SUBJ:3FS	VBP
IV1P+IV	VBP
IV1P+IV+IVSUFF_MOOD:I	VBP
IV1P+IV+IVSUFF_MOOD:J	VBP
IV1P+IV+IVSUFF_MOOD:S	VBP
IV1P+IV_PASS+IVSUFF_MOOD:I	VBN
IV1P+IV_PASS+IVSUFF_MOOD:S	VBN
IV1S+IV	VBP
IV1S+IV+IVSUFF_MOOD:I	VBP
IV1S+IV+IVSUFF_MOOD:J	VBP
IV1S+IV+IVSUFF_MOOD:S	VBP
IV1S+IV_PASS+IVSUFF_MOOD:I	VBN
IV1S+IV_PASS+IVSUFF_MOOD:S	VBN
IV2D+IV+IVSUFF_SUBJ:D_MOOD:I	VBP
IV2D+IV+IVSUFF_SUBJ:D_MOOD:SJ	VBP
IV2FP+IV+IVSUFF_SUBJ:FP	VBP
IV2FS+IV+IVSUFF_SUBJ:2FS_MOOD:I	VBP
IV2FS+IV+IVSUFF_SUBJ:2FS_MOOD:SJ	VBP
IV2FS+IV_PASS+IVSUFF_MOOD:I	VBN
IV2FS+IV_PASS+IVSUFF_MOOD:S	VBN
IV2MP+IV+IVSUFF_SUBJ:MP_MOOD:I	VBP
IV2MP+IV+IVSUFF_SUBJ:MP_MOOD:SJ	VBP
IV2MS+IV	VBP
IV2MS+IV+IVSUFF_MOOD:I	VBP
IV2MS+IV+IVSUFF_MOOD:J	VBP
IV2MS+IV+IVSUFF_MOOD:S	VBP
IV2MS+IV_PASS+IVSUFF_MOOD:I	VBN
IV2MS+IV_PASS+IVSUFF_MOOD:J	VBN
IV2MS+IV_PASS+IVSUFF_MOOD:S	VBN
IV3FD+IV+IVSUFF_SUBJ:D_MOOD:I	VBP
IV3FD+IV+IVSUFF_SUBJ:D_MOOD:SJ	VBP
IV3FP+IV+IVSUFF_SUBJ:FP	VBP
IV3FS+IV	VBP
IV3FS+IV+IVSUFF_MOOD:I	VBP
IV3FS+IV+IVSUFF_MOOD:J	VBP
IV3FS+IV+IVSUFF_MOOD:S	VBP
IV3FS+IV+IVSUFF_SUBJ:3FS	VBP
IV3FS+IV_PASS	VBN
IV3FS+IV_PASS+IVSUFF_MOOD:I	VBN
IV3FS+IV_PASS+IVSUFF_MOOD:J	VBN
IV3FS+IV_PASS+IVSUFF_MOOD:S	VBN
IV3MD+IV+IVSUFF_SUBJ:D_MOOD:I	VBP
IV3MD+IV+IVSUFF_SUBJ:D_MOOD:SJ	VBP
IV3MD+IV_PASS+IVSUFF_SUBJ:D_MOOD:I	VBN
IV3MD+IV_PASS+IVSUFF_SUBJ:D_MOOD:SJ	VBN
IV3MP+IV+IVSUFF_MOOD:I	VBP
IV3MP+IV+IVSUFF_MOOD:S	VBP
IV3MP+IV+IVSUFF_SUBJ:MP_MOOD:I	VBP
IV3MP+IV+IVSUFF_SUBJ:MP_MOOD:SJ	VBP
IV3MP+IV_PASS+IVSUFF_MOOD:I	VBN
IV3MP+IV_PASS+IVSUFF_SUBJ:MP_MOOD:I	VBN
IV3MP+IV_PASS+IVSUFF_SUBJ:MP_MOOD:SJ	VBN
IV3MS+IV	VBP
IV3MS+IV+IVSUFF_MOOD:I	VBP
IV3MS+IV+IVSUFF_MOOD:J	VBP
IV3MS+IV+IVSUFF_MOOD:S	VBP
IV3MS+IV_PASS	VBN
IV3MS+IV_PASS+IVSUFF_MOOD:I	VBN
IV3MS+IV_PASS+IVSUFF_MOOD:J	VBN
IV3MS+IV_PASS+IVSUFF_MOOD:S	VBN
IV_PASS	VBN
JUS+IV1P+IV+IVSUFF_MOOD:J	VBP
JUS+IV2FS+IV+IVSUFF_SUBJ:2FS_MOOD:SJ	VBP
JUS+IV2MS+IV+IVSUFF_MOOD:J	VBP
JUS+IV3FS+IV+IVSUFF_MOOD:J	VBP
JUS+IV3MP+IV+IVSUFF_MOOD:J	VBP
JUS+IV3MP+IV+IVSUFF_SUBJ:MP_MOOD:SJ	VBP
JUS+IV3MS+IV+IVSUFF_MOOD:J	VBP
JUS+IV3MS+IV_PASS+IVSUFF_MOOD:J	VBN
PV	VBD
PV+PVSUFF_3MS	VBD
PV+PVSUFF_SUBJ:1P	VBD
PV+PVSUFF_SUBJ:1S	VBD
PV+PVSUFF_SUBJ:2FS	VBD
PV+PVSUFF_SUBJ:2MP	VBD
PV+PVSUFF_SUBJ:2MS	VBD
PV+PVSUFF_SUBJ:3FD	VBD
PV+PVSUFF_SUBJ:3FP	VBD
PV+PVSUFF_SUBJ:3FS	VBD
PV+PVSUFF_SUBJ:3MD	VBD
PV+PVSUFF_SUBJ:3MP	VBD
PV+PVSUFF_SUBJ:3MS	VBD
PV_PASS	VBN
PV_PASS+PVSUFF_SUBJ:1P	VBN
PV_PASS+PVSUFF_SUBJ:1S	VBN
PV_PASS+PVSUFF_SUBJ:3FD	VBN
PV_PASS+PVSUFF_SUBJ:3FP	VBN
PV_PASS+PVSUFF_SUBJ:3FS	VBN
PV_PASS+PVSUFF_SUBJ:3MD	VBN
PV_PASS+PVSUFF_SUBJ:3MP	VBN
PV_PASS+PVSUFF_SUBJ:3MS	VBN
VERB	VBP


;; Verb particles
JUS_PART	VRP
NEG_PART	VRP
FUT_PART	VRP
PART	VRP
RC_PART	VRP
RESTRIC_PART	VRP
VERB_PART	VRP

;; Inna and her sisters
;; Where SUB_CONJ is "that" heading SBAR, but we can't tell the difference
;;  after orthographic normalization
;; Consider more splits here
PSEUDO_VERB	PSEUDO_VERB
SUB_CONJ	SUB_CONJ

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Prepositions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
PREP	IN

)
