#!/usr/bin/env bash

# Reads a dataset with available integrated files and
# outputs data in the format required for training the
# Stanford Arabic segmenter.

set -e

if [ "$#" -lt 3 ]; then
    echo "Usage: `basename $0` <atb_base> <splits_dir> <output_prefix> [<domain>]"
    exit 1
fi

ATB_BASE=$1
SPLITS=$2
OUTPUT=$3
DOMAIN=$4

for SPLIT in dev train test
do

# Get absolute paths of integrated files
  cat ${SPLITS}/${SPLIT} | xargs -r -n 1 find ${ATB_BASE}/*/data/integrated -name | \

# Run them through the parse_integrated script to output training data 
  xargs -r cat | "`dirname $0`/parse_integrated" > ${OUTPUT}-${SPLIT}.utf8.txt

  if [ "$DOMAIN" != "" ]; then
    sed "s/^/$DOMAIN /" ${OUTPUT}-${SPLIT}.utf8.txt > ${OUTPUT}-withDomains-${SPLIT}.utf8.txt ;
  fi

done
